// schema/pole.js — 杆塔完整字段定义
export default {
  deviceType: 'pole',
  label: '杆塔',
  icon: '/static/icons/pole.png',
  category: '10kV',
  nameField: 'pole_name',   // 该字段的值会同步写入 t_device.name
  children: [
    { deviceType: 'pole_switchgear', label: '柱上开关' }
  ],  // 可挂载的子设备类型
  isAvailablePreNode: true,  // 是否出现在上级节点待选
  isPreNodeEditable: true,  // 是否可编辑上级节点
  preNodeFieldName: "上级节点",

  fields: [
    // ===== 基础信息 =====
    {
      key: 'pole_name',
      label: '杆塔名称',
      group: '基础信息',
      type: 'composite-name',
      required: true,
      placeholder: '输入杆塔名称',
      exportOrder: 1,
      exportLabel: '杆塔名称'
    },
    {
      key: 'pole_height',
      label: '杆塔高 (m)',
      group: '基础信息',
      type: 'number',
      required: true,
      isCopyable: true,
      placeholder: '请输入杆塔高度',
      exportOrder: 2,
      exportLabel: '杆塔高 (m)'
    },
    {
      key: 'pole_material',
      label: '杆塔材质',
      group: '基础信息',
      type: 'select',
      required: true,
      isCopyable: true,
      options: [
        { label: '水泥杆', value: '水泥杆' },
        { label: '钢管杆', value: '钢管杆' },
        { label: '角钢塔', value: '角钢塔' },
        { label: '钢管塔', value: '钢管塔' },
        { label: '铁杆', value: '铁杆' },
        { label: '木杆', value: '木杆' }
      ],
      exportOrder: 3,
      exportLabel: '杆塔材质'
    },
    {
      key: 'pole_nature',
      label: '杆塔性质',
      group: '基础信息',
      type: 'select',
      required: true,
      isCopyable: true,
      options: [
        { label: '直线', value: '直线' },
        { label: '耐张', value: '耐张' },
        { label: '起点', value: '起点' },
        { label: '终点', value: '终点' }
      ],
      exportOrder: 4,
      exportLabel: '杆塔性质'
    },

    // ===== 导线信息 =====
    {
      key: 'wire_arrangement',
      label: '导线排列方式',
      group: '导线信息',
      type: 'select',
      isCopyable: true,
      options: [
        { label: '水平', value: '水平' },
        { label: '三角', value: '三角' },
        { label: '垂直', value: '垂直' }
      ],
      exportOrder: 5,
      exportLabel: '导线排列方式'
    },
    {
      key: 'wire_erection_way',
      label: '导线架设方式',
      group: '导线信息',
      type: 'select',
      isCopyable: true,
      options: [
        { label: '架空', value: '架空' },
        { label: '地埋', value: '地埋' },
        { label: '屋顶', value: '屋顶' },
        { label: '悬挂', value: '悬挂' }
      ],
      exportOrder: 6,
      exportLabel: '导线架设方式'
    },
    {
      key: 'wire_circuit_count',
      label: '导线回路数',
      group: '导线信息',
      type: 'select',
      isCopyable: true,
      options: [
        { label: '其他', value: '其他' },
        { label: '单回', value: '单回' },
        { label: '双回', value: '双回' },
        { label: '三回', value: '三回' },
        { label: '四回', value: '四回' },
        { label: '五回', value: '五回' },
        { label: '六回', value: '六回' }
      ],
      exportOrder: 7,
      exportLabel: '导线回路数'
    },
    {
      key: 'wire_circuit_position',
      label: '导线回路位置',
      group: '导线信息',
      type: 'select',
      isCopyable: true,
      options: [
        { label: '其他', value: '其他' },
        { label: '中回', value: '中回' },
        { label: '左回', value: '左回' },
        { label: '右回', value: '右回' },
        { label: '上回', value: '上回' },
        { label: '下回', value: '下回' },
        { label: '左上回', value: '左上回' },
        { label: '左下回', value: '左下回' },
        { label: '右上回', value: '右上回' },
        { label: '右下回', value: '右下回' }
      ],
      exportOrder: 8,
      exportLabel: '导线回路位置'
    },
    {
      key: 'wire_type',
      label: '导线类型',
      group: '导线信息',
      type: 'select',
      isCopyable: true,
      options: [
        { label: '绝缘导线', value: '绝缘导线' },
        { label: '裸导线', value: '裸导线' },
        { label: '电缆', value: '电缆' }
      ],
      exportOrder: 9,
      exportLabel: '导线类型'
    },
    {
      key: 'wire_model',
      label: '导线型号截面',
      group: '导线信息',
      type: 'cascading-select',
      dependsOn: 'wire_type',
      allowCustom: true,
      isCopyable: true,
      optionsMap: {
        '绝缘导线': [
          { label: 'JKLGYJ-10  铝', value: 'JKLGYJ-10  铝' },
          { label: 'JKLGYJ-16  铝', value: 'JKLGYJ-16  铝' },
          { label: 'JKLGYJ-25  铝', value: 'JKLGYJ-25  铝' },
          { label: 'JKLGYJ-35  铝', value: 'JKLGYJ-35  铝' },
          { label: 'JKLGYJ-50  铝', value: 'JKLGYJ-50  铝' },
          { label: 'JKLGYJ-70  铝', value: 'JKLGYJ-70  铝' },
          { label: 'JKLGYJ-95  铝', value: 'JKLGYJ-95  铝' },
          { label: 'JKLGYJ-120  铝', value: 'JKLGYJ-120  铝' },
          { label: 'JKLGYJ-150  铝', value: 'JKLGYJ-150  铝' },
          { label: 'JKLGYJ-185  铝', value: 'JKLGYJ-185  铝' },
          { label: 'JKLGYJ-240  铝', value: 'JKLGYJ-240  铝' },
          { label: 'JKLGYJ-300  铝', value: 'JKLGYJ-300  铝' },
          { label: 'JKLYJ-10  铝', value: 'JKLYJ-10  铝' },
          { label: 'JKLYJ-16  铝', value: 'JKLYJ-16  铝' },
          { label: 'JKLYJ-25  铝', value: 'JKLYJ-25  铝' },
          { label: 'JKLYJ-35  铝', value: 'JKLYJ-35  铝' },
          { label: 'JKLYJ-50  铝', value: 'JKLYJ-50  铝' },
          { label: 'JKLYJ-70  铝', value: 'JKLYJ-70  铝' },
          { label: 'JKLYJ-95  铝', value: 'JKLYJ-95  铝' },
          { label: 'JKLYJ-120  铝', value: 'JKLYJ-120  铝' },
          { label: 'JKLYJ-150  铝', value: 'JKLYJ-150  铝' },
          { label: 'JKLYJ-185  铝', value: 'JKLYJ-185  铝' },
          { label: 'JKLYJ-240  铝', value: 'JKLYJ-240  铝' },
          { label: 'JKLYJ-300  铝', value: 'JKLYJ-300  铝' },
          { label: 'JKYJ-10  铜', value: 'JKYJ-10  铜' },
          { label: 'JKYJ-16  铜', value: 'JKYJ-16  铜' },
          { label: 'JKYJ-25  铜', value: 'JKYJ-25  铜' },
          { label: 'JKYJ-35  铜', value: 'JKYJ-35  铜' },
          { label: 'JKYJ-50  铜', value: 'JKYJ-50  铜' },
          { label: 'JKYJ-70  铜', value: 'JKYJ-70  铜' },
          { label: 'JKYJ-95  铜', value: 'JKYJ-95  铜' },
          { label: 'JKYJ-120  铜', value: 'JKYJ-120  铜' },
          { label: 'JKYJ-150  铜', value: 'JKYJ-150  铜' },
          { label: 'JKYJ-185  铜', value: 'JKYJ-185  铜' },
          { label: 'JKYJ-240  铜', value: 'JKYJ-240  铜' },
          { label: 'JKYJ-300  铜', value: 'JKYJ-300  铜' }
        ],
        '裸导线': [
          { label: 'LGJ-10  铝', value: 'LGJ-10  铝' },
          { label: 'LGJ-16  铝', value: 'LGJ-16  铝' },
          { label: 'LGJ-25  铝', value: 'LGJ-25  铝' },
          { label: 'LGJ-35  铝', value: 'LGJ-35  铝' },
          { label: 'LGJ-50  铝', value: 'LGJ-50  铝' },
          { label: 'LGJ-70  铝', value: 'LGJ-70  铝' },
          { label: 'LGJ-95  铝', value: 'LGJ-95  铝' },
          { label: 'LGJ-120  铝', value: 'LGJ-120  铝' },
          { label: 'LGJ-150  铝', value: 'LGJ-150  铝' },
          { label: 'LGJ-185  铝', value: 'LGJ-185  铝' },
          { label: 'LGJ-210  铝', value: 'LGJ-210  铝' },
          { label: 'LGJ-240  铝', value: 'LGJ-240  铝' },
          { label: 'LGJ-300  铝', value: 'LGJ-300  铝' },
          { label: 'LGJ-400  铝', value: 'LGJ-400  铝' },
          { label: 'LGJ-500  铝', value: 'LGJ-500  铝' },
          { label: 'LGJ-630  铝', value: 'LGJ-630  铝' },
          { label: 'LGJ-800  铝', value: 'LGJ-800  铝' },
          { label: 'LJ-10  铝', value: 'LJ-10  铝' },
          { label: 'LJ-16  铝', value: 'LJ-16  铝' },
          { label: 'LJ-25  铝', value: 'LJ-25  铝' },
          { label: 'LJ-35  铝', value: 'LJ-35  铝' },
          { label: 'LJ-50  铝', value: 'LJ-50  铝' },
          { label: 'LJ-70  铝', value: 'LJ-70  铝' },
          { label: 'LJ-95  铝', value: 'LJ-95  铝' },
          { label: 'LJ-120  铝', value: 'LJ-120  铝' },
          { label: 'LJ-150  铝', value: 'LJ-150  铝' },
          { label: 'LJ-185  铝', value: 'LJ-185  铝' },
          { label: 'LJ-210  铝', value: 'LJ-210  铝' },
          { label: 'LJ-240  铝', value: 'LJ-240  铝' },
          { label: 'LJ-300  铝', value: 'LJ-300  铝' },
          { label: 'LJ-400  铝', value: 'LJ-400  铝' },
          { label: 'LJ-500  铝', value: 'LJ-500  铝' },
          { label: 'LJ-630  铝', value: 'LJ-630  铝' },
          { label: 'LJ-800  铝', value: 'LJ-800  铝' }
        ],
        '电缆': [
          { label: '3*VLV22-25  铝', value: '3*VLV22-25  铝' },
          { label: '3*VLV22-35  铝', value: '3*VLV22-35  铝' },
          { label: '3*VLV22-50  铝', value: '3*VLV22-50  铝' },
          { label: '3*VLV22-70  铝', value: '3*VLV22-70  铝' },
          { label: '3*VLV22-95  铝', value: '3*VLV22-95  铝' },
          { label: '3*VLV22-120  铝', value: '3*VLV22-120  铝' },
          { label: '3*VLV22-150  铝', value: '3*VLV22-150  铝' },
          { label: '3*VLV22-185  铝', value: '3*VLV22-185  铝' },
          { label: '3*VLV22-240  铝', value: '3*VLV22-240  铝' },
          { label: '3*VLV22-300  铝', value: '3*VLV22-300  铝' },
          { label: '3*VLV22-400  铝', value: '3*VLV22-400  铝' },
          { label: '3*VLV22-500  铝', value: '3*VLV22-500  铝' },
          { label: '3*YJLV22-25  铝', value: '3*YJLV22-25  铝' },
          { label: '3*YJLV22-35  铝', value: '3*YJLV22-35  铝' },
          { label: '3*YJLV22-50  铝', value: '3*YJLV22-50  铝' },
          { label: '3*YJLV22-70  铝', value: '3*YJLV22-70  铝' },
          { label: '3*YJLV22-95  铝', value: '3*YJLV22-95  铝' },
          { label: '3*YJLV22-120  铝', value: '3*YJLV22-120  铝' },
          { label: '3*YJLV22-150  铝', value: '3*YJLV22-150  铝' },
          { label: '3*YJLV22-185  铝', value: '3*YJLV22-185  铝' },
          { label: '3*YJLV22-240  铝', value: '3*YJLV22-240  铝' },
          { label: '3*YJLV22-300  铝', value: '3*YJLV22-300  铝' },
          { label: '3*YJLV22-400  铝', value: '3*YJLV22-400  铝' },
          { label: '3*YJLV22-500  铝', value: '3*YJLV22-500  铝' },
          { label: '3*YJLV-25  铝', value: '3*YJLV-25  铝' },
          { label: '3*YJLV-35  铝', value: '3*YJLV-35  铝' },
          { label: '3*YJLV-50  铝', value: '3*YJLV-50  铝' },
          { label: '3*YJLV-70  铝', value: '3*YJLV-70  铝' },
          { label: '3*YJLV-95  铝', value: '3*YJLV-95  铝' },
          { label: '3*YJLV-120  铝', value: '3*YJLV-120  铝' },
          { label: '3*YJLV-150  铝', value: '3*YJLV-150  铝' },
          { label: '3*YJLV-185  铝', value: '3*YJLV-185  铝' },
          { label: '3*YJLV-240  铝', value: '3*YJLV-240  铝' },
          { label: '3*YJLV-300  铝', value: '3*YJLV-300  铝' },
          { label: '3*YJLV-400  铝', value: '3*YJLV-400  铝' },
          { label: '3*YJLV-500  铝', value: '3*YJLV-500  铝' },
          { label: 'YJV22-25  铜', value: 'YJV22-25  铜' },
          { label: 'YJV22-35  铜', value: 'YJV22-35  铜' },
          { label: 'YJV22-50  铜', value: 'YJV22-50  铜' },
          { label: 'YJV22-70  铜', value: 'YJV22-70  铜' },
          { label: 'YJV22-95  铜', value: 'YJV22-95  铜' },
          { label: 'YJV22-120  铜', value: 'YJV22-120  铜' },
          { label: 'YJV22-150  铜', value: 'YJV22-150  铜' },
          { label: 'YJV22-185  铜', value: 'YJV22-185  铜' },
          { label: 'YJV22-240  铜', value: 'YJV22-240  铜' },
          { label: 'YJV22-300  铜', value: 'YJV22-300  铜' },
          { label: 'YJV22-400  铜', value: 'YJV22-400  铜' },
          { label: 'YJV22-500  铜', value: 'YJV22-500  铜' },
          { label: 'ZC-YJV22-25  铜', value: 'ZC-YJV22-25  铜' },
          { label: 'ZC-YJV22-35  铜', value: 'ZC-YJV22-35  铜' },
          { label: 'ZC-YJV22-50  铜', value: 'ZC-YJV22-50  铜' },
          { label: 'ZC-YJV22-70  铜', value: 'ZC-YJV22-70  铜' },
          { label: 'ZC-YJV22-95  铜', value: 'ZC-YJV22-95  铜' },
          { label: 'ZC-YJV22-120  铜', value: 'ZC-YJV22-120  铜' },
          { label: 'ZC-YJV22-150  铜', value: 'ZC-YJV22-150  铜' },
          { label: 'ZC-YJV22-185  铜', value: 'ZC-YJV22-185  铜' },
          { label: 'ZC-YJV22-240  铜', value: 'ZC-YJV22-240  铜' },
          { label: 'ZC-YJV22-300  铜', value: 'ZC-YJV22-300  铜' },
          { label: 'ZC-YJV22-400  铜', value: 'ZC-YJV22-400  铜' },
          { label: 'ZC-YJV22-500  铜', value: 'ZC-YJV22-500  铜' },
          { label: '3*VV22-25  铜', value: '3*VV22-25  铜' },
          { label: '3*VV22-35  铜', value: '3*VV22-35  铜' },
          { label: '3*VV22-50  铜', value: '3*VV22-50  铜' },
          { label: '3*VV22-70  铜', value: '3*VV22-70  铜' },
          { label: '3*VV22-95  铜', value: '3*VV22-95  铜' },
          { label: '3*VV22-120  铜', value: '3*VV22-120  铜' },
          { label: '3*VV22-150  铜', value: '3*VV22-150  铜' },
          { label: '3*VV22-185  铜', value: '3*VV22-185  铜' },
          { label: '3*VV22-240  铜', value: '3*VV22-240  铜' },
          { label: '3*VV22-300  铜', value: '3*VV22-300  铜' },
          { label: '3*VV22-400  铜', value: '3*VV22-400  铜' },
          { label: '3*VV22-500  铜', value: '3*VV22-500  铜' }
        ]
      },
      exportOrder: 10,
      exportLabel: '导线型号截面'
    },

    // ===== 附属设备与其他 =====
    {
      key: 'auxiliary_equipment',
      label: '柱上附属设备',
      group: '附属设备与其他',
      type: 'checkbox',
      options: [
        { label: '其他', value: '其他' },
        { label: '故障指示器', value: '故障指示器' },
        { label: '接地环', value: '接地环' },
        { label: '柱上避雷器', value: '柱上避雷器' }
      ],
      exportOrder: 11,
      exportLabel: '柱上附属设备'
    },
    {
      key: 'remark_1',
      label: '备注1',
      group: '附属设备与其他',
      type: 'textarea',
      maxLength: 500,
      placeholder: '请输入备注',
      exportOrder: 12,
      exportLabel: '备注1'
    },
    {
      key: 'remark_2',
      label: '备注2',
      group: '附属设备与其他',
      type: 'textarea',
      maxLength: 500,
      placeholder: '请输入备注',
      exportOrder: 13,
      exportLabel: '备注2'
    },
    {
      key: 'span_length',
      label: '档距 (m)',
      group: '附属设备与其他',
      type: 'auto-calc',
      calcType: 'distance_from_prev',
      decimal: 2,
      editable: false,
      exportOrder: 14,
      exportLabel: '档距 (m)'
    },
    {
      key: 'longitude',
      label: '经度',
      group: '附属设备与其他',
      type: 'auto-calc',
      calcType: '',
      decimal: 8,
      editable: false,
      exportOrder: 15,
      exportLabel: '经度'
    },
    {
      key: 'latitude',
      label: '纬度',
      group: '附属设备与其他',
      type: 'auto-calc',
      calcType: '',
      decimal: 8,
      editable: false,
      exportOrder: 16,
      exportLabel: '纬度'
    }
  ],

  photoSlots: [
    { key: 'overview', label: '全貌', required: true },
    { key: 'pole_head', label: '杆头', required: false },
    { key: 'nameplate', label: '铭牌', required: false },
    { key: 'wire_load', label: '导线负荷侧', required: false }
  ],
  extraPhotoSlot: true
}